apiVersion: v1
kind: Service
metadata:
  name: loki-external
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - name: http
    port: 3100
    targetPort: 3100
    nodePort: 30100
  selector:
    app.kubernetes.io/name: loki
    app.kubernetes.io/component: single-binary
